veraPDF/veraPDF-rest

- pom.xml
- src/main/java/org/verapdf/rest/app/VeraPdfRestApplication.java
- src/main/java/org/verapdf/rest/resources/ApiResource.java
- src/main/java/org/verapdf/rest/resources/ProfileResource.java
- src/main/java/org/verapdf/rest/resources/ValidateResource.java
PDF/A validation supported:
- added form multipart data support;
- removed unused views; and
- made some methods static.
> REST PDF/A Validation

- README.md
- pom.xml
- src/main/java/org/verapdf/rest/resources/ProfileResource.java
Documentation and basic fixes:
- fixed manifest main class in pom;
- altered GET profile URL; and
- added basic README instructions.
> Added basic documentation

- pom.xml
- src/main/java/org/verapdf/rest/resources/ByteStreamResource.java
- src/main/java/org/verapdf/rest/resources/ValidateResource.java
- src/main/resources/assets/css/verapdf.css
- src/main/resources/assets/js/jquery.bootstrap.wizard.js
- src/main/resources/assets/js/mustache.js
- src/main/resources/assets/js/vera.results.js
- src/main/resources/assets/js/verapdf.js
- src/main/resources/org/verapdf/rest/views/rest-temp.mustache
- src/main/resources/org/verapdf/rest/views/restclient.mustache
- src/main/resources/org/verapdf/rest/views/restclient.mustache.old
- Validation performed in wizard stages.
- Results conversion now in client.
- Mustache HTML rendering for result.
> Feature: validation result display

- README.md
- api URL now api/info;
- instructions to checkout integration branch; and
- profile XML curl URL now /1b not /ids.
> Fixed documentation issues:

- pom.xml
- src/main/java/org/verapdf/rest/app/VeraPdfRestApplication.java
- src/main/java/org/verapdf/rest/resources/ValidateResource.java
- updated dependencies;
- minor warning fixes; and
- improved exception handling.
> FEAT - Support for 0.16 release

- pom.xml
- added dependency for PDF Box repo.
> FIX - Maven repositories

- .gitignore
- src/main/java/org/openpreservation/bytestreams/ByteStreams.java
- src/main/java/org/verapdf/rest/resources/ApiResource.java
- src/main/java/org/verapdf/rest/resources/ByteStreamResource.java
- src/main/java/org/verapdf/rest/resources/HomePageResource.java
- src/main/java/org/verapdf/rest/resources/ProfileResource.java
- src/main/java/org/verapdf/rest/resources/ValidateResource.java
- src/main/java/org/verapdf/rest/resources/ValidationExceptionMapper.java
- src/main/java/org/verapdf/rest/views/RestClientView.java
- added Eclipse bin directory to .gitignore;
- added JavaDoc;
- tidied exception handling; and
- cleaned up compiler warnings.
> FIX - JavaDoc and compiler warnings

- pom.xml
- src/main/java/org/verapdf/rest/resources/ValidateResource.java
- src/main/resources/assets/js/vera.results.js
- src/main/resources/assets/js/verapdf.js
- src/main/resources/org/verapdf/rest/views/restclient.mustache
- added veraPDF GUI Maven dependency;
- updated veraPDF Maven dependencies to 0.21;
- added HTML representation to ValdiateResource;
- added remaining PDF/A flavours to client page;
- improved error handling to report exceptions;
- moved representation format choice button to config;
- removed Mustache template for results rendering;
- HTML now returns standard report fragment; and
- all output now raw results without conversion.
> FEAT - Validation Reporting

- src/main/java/org/verapdf/rest/app/VeraPdfRestApplication.java
- src/main/java/org/verapdf/rest/resources/ValidateResource.java
- increased max reported errors to 100; and
- added Wiki base URL for reporting.
> FIX - HTML reporting:

- README.md
- pom.xml
- src/main/java/org/verapdf/rest/resources/ApiResource.java
- src/main/java/org/verapdf/rest/resources/ProfileResource.java
- src/main/java/org/verapdf/rest/resources/ValidateResource.java
- removed PDFBox validation dependencies;
- added Greenfield version 1.0 dependencies;
- updated HTML report code to use Processor interface;
- updated changed package names;
- updated dropwizard dependencies;
- added a commons-io dependency; and
- removed unused dependencies;
> FIX - Update to Greenfield version 1.0

- pom.xml
- updated `verapdf-validation-model` dependency in `pom.xml` to v1.4.
> FIX - Updated dependencies to v1.4

- Dockerfile
- README.md
- pom.xml
- src/main/java/org/verapdf/rest/resources/ValidateResource.java
- src/main/resources/assets/js/vera.results.js
- src/main/resources/assets/js/verapdf.js
- src/main/resources/org/verapdf/rest/views/restclient.mustache
- updated veraPDF validation and parent versions;
- added REST method to obtain `ComponentDetails` with version information;
- added basic version information in web client page footer;
- updated fasterxml dependency due to security alert from dependabot;
- now using veraPDF GitHub repo for `Dockerfile`;
- tidied javascript lint issues; and
- added note on DockerHub container image in `README.md`.
> FEAT - version footer and updates

- pom.xml
> fix build failure (JCenter URL change to https)

- Dockerfile
- pom.xml
- server.yml
- src/main/java/org/verapdf/rest/app/VeraPdfRestConfiguration.java
- fixed Docker execution so that the config file is used and swagger initialisation works properly;
- updated commons-io, junit and dropwizard-swagger dependencies; and
- fixed creation of Swagger config bundle.
> FIX: minor niggles and security issues

- pom.xml
- src/main/java/org/verapdf/rest/app/VeraPdfRestConfiguration.java
- src/main/java/org/verapdf/rest/resources/ApiResource.java
- src/main/java/org/verapdf/rest/resources/ValidateResource.java
- tied correct swagger version for dropwizard version; and
- fixed a resource close issue for the valiator.
> FIX: Swagger version

- .github/workflows/publish-mvn.yml
- pom.xml
- added workflow to run on merge to integration (assumes merge is tested); and
- added distribution section to POM to publish to GH Maven registry.
> FEAT: Publish integration jars to GH Maven registry

- settings.xml
> Update action for publish to Github Packages

- .github/workflows/test-pr.yml
- pom.xml
- src/main/java/org/verapdf/rest/resources/ApiResource.java
- src/main/resources/assets/js/vera.results.js
- src/main/resources/assets/js/verapdf.js
- src/main/resources/org/verapdf/release/rest.properties
- added a `GET` method `/api/` that returns the server release details;
- added Javascript methods to add server release details to page footer;
- added a properties file, `src/main/resources/org/verapdf/release/rest.properties` for release details; and
- added resource filtering in `pom.xml` to complete template details in release properties file.
> FEAT: Versioning for REST server

- src/main/resources/assets/js/verapdf.js
- src/main/resources/org/verapdf/rest/views/restclient.mustache
> Fixed form data after pager reload

- src/main/resources/assets/js/verapdf.js
- src/main/resources/org/verapdf/rest/views/restclient.mustache
> #17 added download report button

- src/main/resources/assets/css/verapdf.css
- src/main/resources/assets/js/verapdf.js
- src/main/resources/org/verapdf/rest/views/restclient.mustache
> Fixed form issues

- src/main/resources/org/verapdf/rest/views/restclient.mustache
Added links to DockerHub and GitHub
Added disclaimer that this page is to be used for test purposes only
> Added links and disclaimer

- .gitignore
- src/main/java/org/verapdf/rest/resources/ValidateResource.java
- improved documentation for the SHA1 parameter; and
- made exclusion for `verapdf` files/directories more specific as it was rejecting code changes.
> DOC: SHA-1 valdiation parameter

- .github/workflows/push-dockerhub.yml
- Dockerfile
- Dockerfile_dev
- README.md
- charts/verapdf-rest/Chart.yaml
- pom.xml
- src/main/java/org/verapdf/rest/resources/ApiResource.java
- bumped version -> 1.27
- updated maven dependency
- updated readme
> DEV: v1.27

- src/main/resources/org/verapdf/rest/views/restclient.mustache
Reported by @darrendignam thanks.
> FIX: Reference to verapdf/rest image.

- .github/workflows/push-dockerhub.yml
- Dockerfile
- Dockerfile_dev
- README.md
- charts/verapdf-rest/Chart.yaml
- pom.xml
- src/main/java/org/verapdf/rest/resources/ApiResource.java
- bumped version -> 1.29
- updated maven dependency
- updated readme
> DEV: v1.29
